services:
  - type: web
    name: perplexity-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn client:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 